sudo: required

services:
  - docker

language: go
go:
  - 1.9

env:
  matrix:
    - OKARCH=amd64 OSARCH=amd64
    - OKARCH=386 OSARCH=i386
  global:
    - VERSION=${TRAVIS_TAG}
    - GH_USER=${TRAVIS_REPO_SLUG%/*}
    - GH_APP=${TRAVIS_REPO_SLUG#*/}
    - JFROG_CLI_OFFER_CONFIG=false
    # bintray token
    - secure: jJCgu89rmmdjk8IRGSabSt6FrpLV5ZSEZ3KwMSfutNf0kVA85gk/hRqt6Cn9cvrxQzs3zR8flGfu1SBV5F8FVgovgd1rFPGyC/ISbw22iXw1d3IGDrRzy6cBQL4CaHL9xnnjRqA0PQCCyrvxBRrKHlTt7axsqUW9c14CoxwifnAaRRqPnnbd+YhQlV738LApL/9X8myZpxcyDM16ecui9B+ZBxUWVkIJU0FSlcOwTHCKgASXqbEcV5JDrHks/HCqXrrlM86xih2+QIowmf0z+vKrlxB6bOPpr44ZIQtZhfX5L0UZajWGbPwZNBbzGCc12/heg7Vd0h/QZs10798BoWdwpL4gTaLH1jApz66+EkB72fRV8cFZTvJXuJ9UOHNCQxQL/ela9VWZeGjF5DY1KeS6kmorsYMDqv7btNTI2R7L3Cip3kIYOL+m3LaBU5vSlSj94v7m3kMvNQds3+BvOupbehfYuSd2tDPV1C6OlThSr9g34LI+YY1cFSJSkHghdCDx4hNRlnhVsapTZS9FFHXdpf5tWjOnL9A+aanzrSVxPDnVKe0S/gTeoR270AtM/Tpz7F+tBRyrh/K4fdNvg/AzBz+V4cn/jZHDGG7U7gUWD1GisuHhLGia9UX7l6J6BwGlYJpPktT/H25+TWikPsUtUPW0Jz6HM4fMna2trEs=

before_install:
  - sudo add-apt-repository 'deb https://dl.bintray.com/mh-cbon/deb unstable main'
  - sudo apt-get -qq update
  - sudo apt-get install --allow-unauthenticated changelog go-bin-deb fakeroot
  - mkdir -p ${GOPATH}/bin
  - cd ~
  - curl https://glide.sh/get | sh

install:
  - cd $GOPATH/src/github.com/$TRAVIS_REPO_SLUG
  - glide install
  - go install

script:
  - echo "pass"

before_deploy:
  # deb package
  - cd $GOPATH/src/github.com/$TRAVIS_REPO_SLUG
  - mkdir -p build/$OSARCH
  - GOOS=linux go build --ldflags "-X main.VERSION=$VERSION" -o build/$OSARCH/$GH_APP main.go
  - go-bin-deb generate --file deb.json -a $OSARCH --version $VERSION -o $GH_APP-$OSARCH-$VERSION.deb
  # copy the deb for gh release (backward compatibility)
  - cp $GH_APP-$OSARCH-$VERSION.deb $GH_APP-$OKARCH.deb
  # upload to bintray
  - curl -fL https://getcli.jfrog.io | sh
  - ./jfrog bt pc --key=$BTKEY --user=$GH_USER --licenses=MIT --vcs-url=https://github.com/$GH_USER/deb $GH_USER/deb/$GH_APP || echo "package already exists"
  - ./jfrog bt upload --override=true --key $BTKEY --publish=true --deb=unstable/main/$OSARCH $GH_APP-$OSARCH-$VERSION.deb $GH_USER/deb/$GH_APP/$VERSION pool/g/$GH_APP/
  # rpm package
  - docker pull fedora
  - >
    docker run -v $PWD:/mnt/travis fedora /bin/sh -c
    "cd /mnt/travis && (curl -s -L https://bintray.com/mh-cbon/rpm/rpm > /etc/yum.repos.d/w.repo) && dnf install go-bin-rpm changelog rpm-build -y --quiet && go-bin-rpm generate --file rpm.json -a $OSARCH --version $VERSION -o $GH_APP-$OSARCH-$VERSION.rpm"
  # copy the rpm for gh release (backward compatibility)
  - cp $GH_APP-$OSARCH-$VERSION.rpm $GH_APP-$OKARCH.rpm
  # upload to bintray
  - ./jfrog bt pc --key=$BTKEY --user=$GH_USER --licenses=MIT --vcs-url=https://github.com/$GH_USER/rpm $GH_USER/rpm/$GH_APP || echo "package already exists"
  - ./jfrog bt upload --override=true --key $BTKEY --publish=true $GH_APP-$OSARCH-$VERSION.rpm $GH_USER/rpm/$GH_APP/$VERSION pool/$POOL/$GH_APP/
  # generate the repo metadata
  - curl -X POST -u ${GH_USER}:${BTKEY} https://api.bintray.com/calc_metadata/${GH_USER}/rpm

deploy:
  provider: releases
  api_key:
    secure: GpYoHE118Z5P3UmG4KTZZ5pYm/0MuFIcmXkBi19ERt32WvzBYOO8HDN91aMux0h/FUUegG5d2TeLaZzS01uYyDO6Okw3Whbpt1Xj9f7hCEh72Xrvvkl+HsnFRtQZnrI22HF7g/5dN404GGSXjFMj4yDbigJE0zxyHqyFphqIckUDACI3sdrbzJ4RP9v80dfwF0x935C+O6ciSl0J2fZBpVu83urRKYciXMOolNg1KwulsRAuM4keIQVa5q0qM258DgpM0iImXMwaCWjuQzvOif9mVfMWwi9SRQo1wv6yrEStjq5a9SxFfNX3gbCNdCSIemQkBMAbEYgWFeDASsMDiZzpXIHx62WvGkWprU+s2grsmV4r0uqGvwMCAp4zNaycw7kF0KgSdRpwOuXEUJTBTKLv/hO20oldFAzGSQMGxiy4NOTMu7hrR1o0UG9W/uRTkIYwAp4chCganaFaxLVSNXrY+39fnvDYLlgu6gQlZIiM7OxbLZywQvIY3XL774pVASTfD/u8iHktGJVEiJQi1v7TBA4/tyH5VrAt/5Yn4Jd3QT+d2xohse91Q5rAZJ4Fl/6XhDild6pSLsMasc6NUfxg8niO4xlmafv2ftQuBvOtLTurUsD+VyJEDDTsvueQMlX4AljuD7MgJHJ4ASlgjPysddWxRL5ldoVrSTaEMwg=
  file_glob: true
  file:
    - $GH_APP-$OKARCH.deb
    - $GH_APP-$OKARCH.rpm
  skip_cleanup: true
  on:
    tags: true
